import { NextResponse } from 'next/server';

const RESEND_API_KEY = process.env.RESEND_API_KEY;
const ESCALATION_EMAIL = "techzema@gmail.com";

export async function POST(req: Request) {
    try {
        const { userEmail, userName, reason, transcript } = await req.json();

        // 1. Log to console (always reliable fallback)
        console.log("🚨 ZIVA ESCALATION ALERT 🚨");
        console.log(`User: ${userName} <${userEmail}>`);
        console.log(`Reason: ${reason}`);
        console.log(`Transcript Preview: ${transcript.substring(0, 100)}...`);

        // 2. Send Email if API Key exists
        if (RESEND_API_KEY) {
            const res = await fetch("https://api.resend.com/emails", {
                method: "POST",
                headers: {
                    "Authorization": `Bearer ${RESEND_API_KEY}`,
                    "Content-Type": "application/json"
                },
                body: JSON.stringify({
                    from: "Ziva AI <ziva@ratelshop.com>", // You'll need a verified domain for this to work perfectly on Resend
                    to: ESCALATION_EMAIL,
                    subject: `[Escalation] ${reason} - ${userName}`,
                    html: `
                        <h1>New Support Escalation</h1>
                        <p><strong>User:</strong> ${userName} (${userEmail})</p>
                        <p><strong>Reason:</strong> ${reason}</p>
                        <hr />
                        <h3>Recent Chat Transcript</h3>
                        <pre style="background: #f4f4f4; padding: 10px; border-radius: 5px;">${transcript}</pre>
                        <hr />
                        <p><em>Autogenerated by Ziva AI</em></p>
                    `
                })
            });

            if (!res.ok) {
                console.warn("Resend API failed", await res.text());
            }
        } else {
            console.warn("Skipping email: RESEND_API_KEY not found in env");
        }

        return NextResponse.json({ success: true, message: "Escalation logged successfully" });

    } catch (error) {
        console.error("Escalation Error:", error);
        return NextResponse.json({ success: false, error: "Failed to escalate" }, { status: 500 });
    }
}
