import { Product } from "./types";

export const NIGERIA_TOP_PRODUCTS: Product[] = [
    {
        id: "nj_p1",
        seller_id: "s1",
        seller_name: "TechHub Lagos",
        name: "3 in 1 Laptop Backpack — Anti-theft, USB Charging Port, Water Resistant",
        description: "Premium 3-in-1 laptop backpack perfect for students and professionals. Includes main backpack, sling bag, and purse. Fits up to 15.6-inch laptops. Features USB charging port and anti-theft design.",
        price: 25000,
        original_price: 35000,
        recommended_price: 25000,
        category: "fashion",
        image_url: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=400&h=400",
        images: [],
        stock: 145,
        price_flag: "fair",
        is_active: true,
        avg_rating: 4.8,
        review_count: 532,
        sold_count: 1250,
        created_at: "2025-12-01T10:00:00Z",
        specs: { Brand: "Generic", "Material": "Oxford Cloth", "Waterproof": "Yes", "Capacity": "35L", "Laptop Size": "Up to 15.6 inches", "Features": "USB Port, Headphone Port, Anti-theft lock" },
        highlights: ["Includes 3 pieces: Main backpack, shoulder bag, and small pouch", "Built-in USB charging port for on-the-go power", "Water-resistant material protects your electronics", "Anti-theft combination lock for main compartment"],
    },
    {
        id: "nj_p2",
        seller_id: "s4",
        seller_name: "PhoneZone Nigeria",
        name: "Oraimo FreePods 4 True Wireless Earbuds",
        description: "Active Noise Cancellation, HeavyBass technology, 35.5-hour playtime. The most popular earbuds in Nigeria.",
        price: 22000,
        original_price: 28000,
        recommended_price: 25000,
        category: "electronics",
        image_url: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&q=80&w=400&h=400",
        images: [],
        stock: 320,
        price_flag: "fair",
        is_active: true,
        avg_rating: 4.7,
        review_count: 1420,
        sold_count: 5000,
        created_at: "2025-11-15T10:00:00Z",
        specs: { Brand: "Oraimo", "Model": "FreePods 4", "Playtime": "Up to 35.5 hrs", "Bluetooth": "V5.2", "Water Resistance": "IPX5", "Charging Type": "Type-C" },
        highlights: ["Active Noise Cancellation blocks up to 30dB", "Oraimo exclusive HeavyBass technology", "Transparency mode lets in ambient sound", "Companion app for custom EQ settings"],
    },
    {
        id: "nj_p3",
        seller_id: "s5",
        seller_name: "Lagos Gadget World",
        name: "Oraimo 20000mAh Power Bank (Toast 10 Flash)",
        description: "20000mAh high capacity portable charger. Dual output, fast charging, universally compatible.",
        price: 18500,
        original_price: 22000,
        recommended_price: 18000,
        category: "electronics",
        image_url: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&q=80&w=400&h=400",
        images: [],
        stock: 500,
        price_flag: "fair",
        is_active: true,
        avg_rating: 4.8,
        review_count: 2150,
        sold_count: 8500,
        created_at: "2025-10-10T10:00:00Z",
        specs: { Brand: "Oraimo", "Capacity": "20000mAh", "Output": "5V 2.1A (Dual)", "Input": "Micro USB / Type-C", "Thickness": "16mm" },
        highlights: ["Massive 20000mAh capacity provides weeks of power", "Dual fast charging output for simultaneous device charging", "Anti-scratch texture and elegant design", "Multiprotect safety system"],
    },
    {
        id: "nj_p4",
        seller_id: "s1",
        seller_name: "TechHub Lagos",
        name: "Starlink Standard Kit (Gen 2)",
        description: "High-speed, low-latency broadband internet across Nigeria. Perfect for remote work, streaming, and gaming.",
        price: 800000,
        original_price: 850000,
        recommended_price: 800000,
        category: "electronics",
        image_url: "https://images.unsplash.com/photo-1683457591605-6441dd8cbf34?auto=format&fit=crop&q=80&w=400&h=400",
        images: [],
        stock: 45,
        price_flag: "fair",
        is_active: true,
        avg_rating: 4.8,
        review_count: 850,
        sold_count: 2100,
        created_at: "2025-12-05T10:00:00Z",
        specs: { Brand: "Starlink", "Model": "Standard Kit", "Type": "Satellite Dish & Router", "Speed": "50-200 Mbps", "Latency": "20-40ms", "Coverage": "Global/Nigeria" },
        highlights: ["High-speed satellite internet anywhere in Nigeria", "Easy self-install kit includes dish, router, cable and base", "Dual band Wi-Fi 5 router for strong home coverage", "Durable design withstands extreme weather"],
    },
    {
        id: "nj_p5",
        seller_id: "s7",
        seller_name: "Mama Nkechi Home Needs",
        name: "Silver Crest Extra Large Commercial Blender 4500W",
        description: "Heavy duty 4500W blender. Crushes ice, beans, and nuts in seconds. 2L unbreakable jar.",
        price: 25000,
        original_price: 35000,
        recommended_price: 28000,
        category: "home",
        image_url: "https://images.unsplash.com/photo-1585237832863-793db53907eb?auto=format&fit=crop&q=80&w=400&h=400",
        images: [],
        stock: 210,
        price_flag: "fair",
        is_active: true,
        avg_rating: 4.6,
        review_count: 640,
        sold_count: 3200,
        created_at: "2025-11-20T10:00:00Z",
        specs: { Brand: "Silver Crest", "Power": "4500 Watts", "Capacity": "2 Liters", "Blades": "6 Stainless Steel Pro Blades", "Speeds": "Variable Speed with Pulse" },
        highlights: ["Massive 4500W motor easily grinds beans, seeds and ice", "Unbreakable 2L polycarbonate jar", "6-blade stainless steel assembly for smooth blending", "Overheat protection safety system"],
    },
    {
        id: "nj_p6",
        seller_id: "s2",
        seller_name: "EV & Power Hub",
        name: "Qasa 18-inch Rechargeable Standing Fan",
        description: "18-inch rechargeable fan with remote control, LED light, and USB port. Stay cool during power outages.",
        price: 55000,
        original_price: 65000,
        recommended_price: 58000,
        category: "home",
        image_url: "https://images.unsplash.com/photo-1565151443833-28dece2763f0?auto=format&fit=crop&q=80&w=400&h=400",
        images: [],
        stock: 85,
        price_flag: "fair",
        is_active: true,
        avg_rating: 4.5,
        review_count: 340,
        sold_count: 1500,
        created_at: "2025-10-25T10:00:00Z",
        specs: { Brand: "Qasa", "Size": "18 Inches", "Battery": "12V 4.5Ah Lead-Acid", "Duration": "Up to 8 hours", "Features": "USB port, LED night light, Remote control" },
        highlights: ["Powerful 5-blade 18-inch fan for maximum airflow", "Built-in battery provides up to 8 hours of cooling", "Remote control for convenience", "Includes USB port to charge your phone during outages"],
    },
    {
        id: "nj_p7",
        seller_id: "s4",
        seller_name: "PhoneZone Nigeria",
        name: "Tecno Spark 20 Pro 256GB / 8GB RAM",
        description: "108MP ultra-sensing camera, 120Hz display, Helio G99 processor. Best value smartphone.",
        price: 245000,
        original_price: 265000,
        recommended_price: 250000,
        category: "phones",
        image_url: "https://images.unsplash.com/photo-1598327105666-5b89351cb31b?auto=format&fit=crop&q=80&w=400&h=400",
        images: [],
        stock: 65,
        price_flag: "fair",
        is_active: true,
        avg_rating: 4.7,
        review_count: 420,
        sold_count: 1800,
        created_at: "2025-11-30T10:00:00Z",
        specs: { Brand: "Tecno", "Model": "Spark 20 Pro", "Storage": "256GB", "RAM": "8GB (Up to 16GB extended)", "Camera": "108MP Main + 32MP Selfie", "Battery": "5000mAh, 33W Fast Charge", "Processor": "Helio G99 Ultimate" },
        highlights: ["108MP ultra-clear main camera for stunning photos", "Massive 256GB storage and up to 16GB extended RAM", "Smooth 120Hz hole-screen display", "Premium design with 33W super charge"],
    },
    {
        id: "nj_p8",
        seller_id: "s4",
        seller_name: "PhoneZone Nigeria",
        name: "Infinix Note 40 Pro 256GB / 8GB RAM",
        description: "Amoled 120Hz display, 70W All-Round FastCharge 2.0, 108MP OIS camera. The ultimate fast charging phone.",
        price: 385000,
        original_price: 410000,
        recommended_price: 390000,
        category: "phones",
        image_url: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&q=80&w=400&h=400",
        images: [],
        stock: 45,
        price_flag: "fair",
        is_active: true,
        avg_rating: 4.8,
        review_count: 280,
        sold_count: 950,
        created_at: "2025-12-05T10:00:00Z",
        specs: { Brand: "Infinix", "Model": "Note 40 Pro", "Storage": "256GB", "RAM": "8GB", "Display": "6.78\" 3D Curved AMOLED 120Hz", "Charging": "70W Wired + 20W Wireless", "Camera": "108MP OIS Super-Zoom" },
        highlights: ["Incredible 70W multi-speed fast charging and 20W wireless charging", "Stunning 3D curved 120Hz AMOLED display", "108MP camera with Optical Image Stabilization (OIS)", "Active Halo AI lighting design"],
    },
    {
        id: "nj_p9",
        seller_id: "s7",
        seller_name: "Mama Nkechi Home Needs",
        name: "Hisense 43-inch Smart Full HD TV",
        description: "A4 Series Smart TV. Netflix, YouTube, Prime Video built-in. Vivid colors and crisp sound.",
        price: 265000,
        original_price: 300000,
        recommended_price: 275000,
        category: "electronics",
        image_url: "https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&q=80&w=400&h=400",
        images: [],
        stock: 25,
        price_flag: "fair",
        is_active: true,
        avg_rating: 4.5,
        review_count: 510,
        sold_count: 2200,
        created_at: "2025-10-15T10:00:00Z",
        specs: { Brand: "Hisense", "Size": "43 Inches", "Resolution": "Full HD (1920x1080)", "Smart OS": "VIDAA U5", "Connectivity": "Wi-Fi, 2x HDMI, 2x USB", "Sound": "DTS Virtual:X" },
        highlights: ["Smart TV includes Netflix, YouTube, Prime Video apps", "Natural color enhancer for vibrant picture quality", "DTS Virtual:X creates immersive surround sound experience", "Bezel-less design maximizes viewing area"],
    },
    {
        id: "nj_p10",
        seller_id: "s1",
        seller_name: "TechHub Lagos",
        name: "HP 15 Laptop - Intel Celeron N4020, 8GB RAM, 512GB SSD",
        description: "Affordable student and office laptop. Reliable performance, long battery life, lightweight design.",
        price: 360000,
        original_price: 400000,
        recommended_price: 375000,
        category: "computers",
        image_url: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&q=80&w=400&h=400",
        images: [],
        stock: 35,
        price_flag: "fair",
        is_active: true,
        avg_rating: 4.3,
        review_count: 320,
        sold_count: 1500,
        created_at: "2025-11-10T10:00:00Z",
        specs: { Brand: "HP", "Model": "15-dw series", "Processor": "Intel Celeron N4020", "RAM": "8GB DDR4", "Storage": "512GB PCIe NVMe SSD", "Display": "15.6\" HD Micro-edge", "OS": "Windows 11 Home" },
        highlights: ["Great budget laptop for students and office workers", "Fast 512GB SSD for quick boot times and app loading", "Large 15.6-inch display with micro-edge bezel", "Long-lasting battery with HP Fast Charge"],
    },
    {
        id: "nj_p11",
        seller_id: "s8",
        seller_name: "Glow & Shine Beauty",
        name: "Dr. Rashel Vitamin C Face Serum",
        description: "Anti-aging and brightening skin care serum. Contains hyaluronic acid. Fades sun spots and discoloration.",
        price: 6500,
        original_price: 8500,
        recommended_price: 6500,
        category: "beauty",
        image_url: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=400&h=400",
        images: [],
        stock: 500,
        price_flag: "fair",
        is_active: true,
        avg_rating: 4.4,
        review_count: 1250,
        sold_count: 8500,
        created_at: "2025-09-20T10:00:00Z",
        specs: { Brand: "Dr. Rashel", "Volume": "50ml", "Key Ingredients": "Vitamin C, Hyaluronic Acid", "Skin Type": "All Skin Types", "Benefits": "Brightening, Anti-aging, Hydrating" },
        highlights: ["Highly effective antioxidant prevents environmental skin damage", "Hyaluronic acid provides deep and natural moisturizing", "Visibly brightens skin and evens out tone", "Reduces appearance of wrinkles and fine lines"],
    },
    {
        id: "nj_p12",
        seller_id: "s8",
        seller_name: "Glow & Shine Beauty",
        name: "Nivea Radiant & Beauty Advanced Care Lotion",
        description: "Formulated specifically for melanin-rich skin. 48h deep moisture, evens skin tone.",
        price: 6500,
        original_price: 7500,
        recommended_price: 6500,
        category: "beauty",
        image_url: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&q=80&w=400&h=400",
        images: [],
        stock: 400,
        price_flag: "fair",
        is_active: true,
        avg_rating: 4.8,
        review_count: 890,
        sold_count: 4500,
        created_at: "2025-10-05T10:00:00Z",
        specs: { Brand: "Nivea", "Size": "400ml", "Key Ingredients": "5 Oils (Almond, Soybean, Avocado, Macadamia, Olive) + Vitamins", "Skin Type": "Dry and Very Dry Skin", "Formula": "For Melanin Rich Skin" },
        highlights: ["Specifically formulated for the needs of melanin rich skin", "Visibly reduces the appearance of stretch marks", "Enriched with 5 natural oils and vitamins", "Provides intensive 48-hour moisture"],
    },
    {
        id: "nj_p13",
        seller_id: "s6",
        seller_name: "Luxe Fashion House",
        name: "Bone Straight 100% Human Hair Wig - 24 Inches",
        description: "Super double drawn bone straight human hair. T-part lace closure, silkiest texture. Tangle-free.",
        price: 180000,
        original_price: 220000,
        recommended_price: 195000,
        category: "fashion",
        image_url: "https://images.unsplash.com/photo-1605980776566-0486c3ac7617?auto=format&fit=crop&q=80&w=400&h=400",
        images: [],
        stock: 25,
        price_flag: "fair",
        is_active: true,
        avg_rating: 4.6,
        review_count: 210,
        sold_count: 650,
        created_at: "2025-11-15T10:00:00Z",
        specs: { Brand: "Generic", "Material": "100% Virgin Human Hair", "Style": "Bone Straight", "Length": "24 Inches", "Weight": "300g", "Color": "Natural Black (1B)" },
        highlights: ["100% unprocessed virgin human hair, cut from single donor", "Super double drawn for fullness from root to tip", "Can be bleached, dyed, permed, and restyled", "Shedding and tangle free with proper care"],
    },
    {
        id: "nj_p14",
        seller_id: "s7",
        seller_name: "Mama Nkechi Home Needs",
        name: "12.5Kg Standard empty Gas Cylinder",
        description: "Durable and safe 12.5kg empty cooking gas cylinder for family homes. Anti-rust paint.",
        price: 28000,
        original_price: 32000,
        recommended_price: 28500,
        category: "home",
        image_url: "https://images.unsplash.com/photo-1621539659050-c6519eb608c0?auto=format&fit=crop&q=80&w=400&h=400",
        images: [],
        stock: 120,
        price_flag: "fair",
        is_active: true,
        avg_rating: 4.5,
        review_count: 145,
        sold_count: 850,
        created_at: "2025-12-10T10:00:00Z",
        specs: { Brand: "Generic", "Capacity": "12.5 Kg", "Valve Type": "Camping/Standard 20mm", "Material": "Carbon Steel", "Test Pressure": "3.2 MPa" },
        highlights: ["Standard 12.5kg capacity ideal for family cooking demands", "Built with high-quality carbon steel for maximum safety", "Coated with durable anti-rust paint for longevity", "Compatible with standard Nigerian gas regulators"],
    },
    {
        id: "nj_p15",
        seller_id: "s13",
        seller_name: "SportyNaija",
        name: "Super Eagles 2024/2025 Home Jersey",
        description: "Official replica of the Nigeria National Team home jersey. Breathable, sweat-wicking fabric.",
        price: 25000,
        original_price: 35000,
        recommended_price: 30000,
        category: "sports",
        image_url: "https://images.unsplash.com/photo-1554526279-3fb7ebed99c4?auto=format&fit=crop&q=80&w=400&h=400",
        images: [],
        stock: 300,
        price_flag: "fair",
        is_active: true,
        avg_rating: 4.8,
        review_count: 560,
        sold_count: 2400,
        created_at: "2025-10-20T10:00:00Z",
        specs: { Brand: "Nike", "Team": "Nigeria Super Eagles", "Type": "Replica Home Shirt", "Material": "100% Polyester", "Fit": "Standard fit for a relaxed, easy feel" },
        highlights: ["Nike Dri-FIT technology moves sweat away from your skin", "Replica design modeled after what the pros wear on the pitch", "Embroidered Super Eagles crest and Nike swoosh", "Lightweight, highly breathable fabric"],
    }
];

export const generateMoreDemoProducts = (): Product[] => {
    // We duplicate and slightly alter the top 15 to make up to 35 more, resulting in 50 total added
    const more: Product[] = [];
    const categories = ["electronics", "computers", "phones", "fashion", "home", "fitness", "beauty", "sports", "cars", "energy"];

    for (let i = 16; i <= 50; i++) {
        const baseProduct = NIGERIA_TOP_PRODUCTS[i % NIGERIA_TOP_PRODUCTS.length];
        const newPrice = Math.round(baseProduct.price * (0.8 + Math.random() * 0.5) / 1000) * 1000;
        more.push({
            ...baseProduct,
            id: `nj_p${i}`,
            name: `${baseProduct.name} - Variant ${i}`,
            price: newPrice,
            original_price: Math.round(newPrice * 1.2),
            recommended_price: newPrice,
            stock: Math.floor(Math.random() * 200) + 10,
            review_count: Math.floor(Math.random() * 500),
            sold_count: Math.floor(Math.random() * 1000),
            created_at: new Date(Date.now() - Math.random() * 10000000000).toISOString(),
            is_sponsored: Math.random() > 0.8,
        });
    }

    return [...NIGERIA_TOP_PRODUCTS, ...more];
};
